# Generated by Django 3.0.10 on 2021-04-18 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='media/images/', verbose_name='Set a portfolio image')),
                ('name', models.CharField(max_length=200, verbose_name='Enter your Name')),
                ('d_o_b', models.DateField(auto_now=True, verbose_name='Date of Birth')),
                ('e_mail', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('contact', models.CharField(max_length=10, verbose_name='Contact No. :')),
                ('city', models.CharField(max_length=100, verbose_name='Enter city')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=200)),
                ('resume', models.FileField(null=True, upload_to='media/files/')),
                ('tagline', models.CharField(max_length=200, null=True, verbose_name='Do you want to add a tagline ')),
                ('desc', models.TextField(null=True, verbose_name='Describe yourself')),
            ],
        ),
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_name', models.CharField(max_length=300, verbose_name='Enter your name')),
                ('query_email', models.EmailField(max_length=254, verbose_name='Your E mail ID')),
                ('query_contact', models.CharField(max_length=10, null=True, verbose_name='Enter your phone number')),
                ('query_desc', models.TextField(verbose_name='Write your query')),
            ],
        ),
        migrations.CreateModel(
            name='trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img6', models.ImageField(null=True, upload_to='media/images/', verbose_name='Do you want Set a  image')),
                ('traits_in', models.CharField(max_length=1000, null=True, verbose_name='Enter the list of  your traits')),
                ('name6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Intro')),
            ],
        ),
        migrations.CreateModel(
            name='social_url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_icon', models.CharField(choices=[('fa fa-github', 'fa fa-github'), ('fa fa-linkedin-square', 'fa fa-linkedin-square'), ('fa fa-facebook-official', 'fa fa-facebook-official'), ('fa fa-instagram', 'fa fa-instagram'), ('fa fa-codepen', 'fa fa-codepen'), ('fa fa-google-plus-official', 'fa fa-google-plus-official'), ('fa fa-jsfiddle', 'fa fa-jsfiddle'), ('fa fa-medium', 'fa fa-medium'), ('fa fa-pinterest', 'fa fa-pinterest'), ('fa fa-quora', 'fa fa-quora'), ('fa fa-reddit', 'fa fa-reddit'), ('fa fa-scribd', 'fa fa-scribd'), ('fa fa-snapchat', 'fa fa-snapchat'), ('fa fa-skype', 'fa fa-skype'), ('fa fa-slideshare', 'fa fa-slideshare'), ('fa fa-slack', 'fa fa-slack'), ('fa fa-stack-overflow', 'fa fa-stack-overflow'), ('fa fa-telegram', 'fa fa-telegram'), ('fa fa-twitter', 'fa fa-twitter'), ('fa fa-tumblr-square', 'fa fa-tumblr-square'), ('fa fa-whatsapp', 'fa fa-whatsapp'), ('fa fa-wordpress', 'fa fa-wordpress'), ('fa fa-yahoo', 'fa fa-yahoo'), ('fa fa-youtube', 'fa fa-youtube')], max_length=200)),
                ('url_link', models.URLField(null=True, verbose_name='any social URL link (facebook,github,linkedin,instagram etc)')),
                ('is_show5', models.BooleanField(verbose_name='Do you want to show it on portfolio')),
                ('name8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Intro')),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img5', models.ImageField(null=True, upload_to='media/images/', verbose_name='Do you want Set a  image')),
                ('skill_in', models.CharField(max_length=1000, null=True, verbose_name='Enter the list of  your skill')),
                ('name5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Intro')),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img7', models.ImageField(null=True, upload_to='media/images/', verbose_name='Do you want Set a  image')),
                ('project_name', models.CharField(max_length=200, null=True, verbose_name='Enter the tittle for your project')),
                ('project_tech', models.CharField(max_length=300, null=True, verbose_name='Main Technology used in your project')),
                ('software', models.CharField(max_length=500, null=True, verbose_name='List the key software(python,flask,selenium etc)')),
                ('proj_url', models.URLField(verbose_name='Do you want to add a link of your project like git or any other')),
                ('start_date', models.DateField(auto_now=True, null=True, verbose_name='Started project on')),
                ('end_date', models.DateField(auto_now=True, null=True, verbose_name='Project ended on')),
                ('proj_desc', models.TextField(null=True, verbose_name='Project description')),
                ('is_show4', models.BooleanField(verbose_name='Do you want to show it on portfolio')),
                ('name7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Intro')),
            ],
        ),
        migrations.CreateModel(
            name='key_specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img2', models.ImageField(null=True, upload_to='media/images/', verbose_name='Do you want Set a  image')),
                ('specialization_in', models.CharField(max_length=200, null=True, verbose_name='Enter the technology in which you are specialized')),
                ('is_show1', models.BooleanField(verbose_name='Do you want to show it on portfolio')),
                ('name2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Intro')),
            ],
        ),
        migrations.CreateModel(
            name='key_achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img4', models.ImageField(null=True, upload_to='media/images/', verbose_name='Do you want Set a  image')),
                ('achievement_in', models.CharField(max_length=1000, null=True, verbose_name='Enter your achievements')),
                ('is_show3', models.BooleanField(verbose_name='Do you want to show it on portfolio')),
                ('name4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Intro')),
            ],
        ),
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name1', models.CharField(max_length=200, null=True, verbose_name='Enter Company name you worked as employee')),
                ('post1', models.CharField(max_length=200, null=True, verbose_name='Enter the post ')),
                ('package', models.CharField(max_length=200, null=True)),
                ('start_date2', models.DateField(auto_now=True, null=True, verbose_name='Started project on')),
                ('end_date2', models.DateField(auto_now=True, null=True, verbose_name='Project ended on')),
                ('is_show7', models.BooleanField(verbose_name='Do you want to show it on portfolio')),
                ('name10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Intro')),
            ],
        ),
        migrations.CreateModel(
            name='internships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, null=True, verbose_name='Enter Company name')),
                ('post', models.CharField(max_length=200, null=True, verbose_name='Enter the post ')),
                ('start_date1', models.DateField(auto_now=True, null=True, verbose_name='Started project on')),
                ('end_date1', models.DateField(auto_now=True, null=True, verbose_name='Project ended on')),
                ('is_show6', models.BooleanField(verbose_name='Do you want to show it on portfolio')),
                ('name9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Intro')),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(null=True, upload_to='media/images/', verbose_name='Do you want Set a  image')),
                ('qualification', models.CharField(max_length=100, verbose_name='Enter your qualification (10h,12th,BCA,MCA etc)')),
                ('institute', models.CharField(max_length=300, verbose_name='Institute Name')),
                ('Affiliated_to', models.CharField(max_length=200, verbose_name='Affiliated to (CBSE,GGISPU,SHARDA etc)')),
                ('Year_pass', models.CharField(max_length=4, verbose_name='Year of passing')),
                ('Result', models.CharField(max_length=5, verbose_name='Enter the result (percentage ,CGPA)')),
                ('is_pursuing', models.BooleanField(verbose_name=' True if Pursuing')),
                ('is_show', models.BooleanField(verbose_name='Do you want to show it on portfolio')),
                ('name1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Intro')),
            ],
        ),
        migrations.CreateModel(
            name='certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img3', models.ImageField(null=True, upload_to='media/images/', verbose_name='Do you want Set a  image')),
                ('certificate_name', models.CharField(max_length=100, null=True, verbose_name='Got certificate in')),
                ('certificate_from', models.CharField(max_length=200, null=True, verbose_name='Got certificate from')),
                ('Certificate_on', models.DateField(auto_now=True, null=True, verbose_name='Certificate got on')),
                ('is_show2', models.BooleanField(verbose_name='Do you want to show it on portfolio')),
                ('name3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Intro')),
            ],
        ),
    ]
