# Generated by Django 3.0.10 on 2021-04-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='key_achievements',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='key_specialization',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='img5',
        ),
        migrations.RemoveField(
            model_name='trait',
            name='img6',
        ),
        migrations.AddField(
            model_name='certification',
            name='certificate_url',
            field=models.URLField(null=True, verbose_name='Any URL of certificate or anything'),
        ),
        migrations.AddField(
            model_name='internships',
            name='c_img1',
            field=models.ImageField(null=True, upload_to='media/images/', verbose_name='Do you want to upload a image'),
        ),
        migrations.AddField(
            model_name='internships',
            name='is_working',
            field=models.BooleanField(default=True, verbose_name='Tick if currently working'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internships',
            name='linkedin_1_url',
            field=models.URLField(null=True, verbose_name="Enter company's Linkedin Profile"),
        ),
        migrations.AddField(
            model_name='intro',
            name='exp',
            field=models.PositiveIntegerField(null=True, verbose_name='Experience (Years)'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='c_img2',
            field=models.ImageField(null=True, upload_to='media/images/'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='is_working1',
            field=models.BooleanField(default=True, verbose_name='Tick if currently working'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='linkedin_2_url',
            field=models.URLField(null=True, verbose_name="Enter company's Linkedin Profile"),
        ),
        migrations.AddField(
            model_name='projects',
            name='is_upcoming',
            field=models.BooleanField(default=True, verbose_name='Tick if upcoming'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='is_work',
            field=models.BooleanField(default=True, verbose_name='Tick if workking on it'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='Affiliated_to',
            field=models.CharField(max_length=200, null=True, verbose_name='Affiliated to (CBSE,GGISPU,SHARDA etc)'),
        ),
        migrations.AlterField(
            model_name='education',
            name='Result',
            field=models.CharField(max_length=5, null=True, verbose_name='Enter the result (percentage ,CGPA)'),
        ),
        migrations.AlterField(
            model_name='education',
            name='Year_pass',
            field=models.CharField(max_length=4, null=True, verbose_name='Year of passing'),
        ),
        migrations.AlterField(
            model_name='education',
            name='institute',
            field=models.CharField(max_length=300, null=True, verbose_name='Institute Name'),
        ),
        migrations.AlterField(
            model_name='education',
            name='qualification',
            field=models.CharField(max_length=100, null=True, verbose_name='Enter your qualification (10h,12th,BCA,MCA etc)'),
        ),
        migrations.AlterField(
            model_name='social_url',
            name='class_icon',
            field=models.CharField(choices=[('fa fa-github', 'fa fa-github'), ('fa fa-linkedin-square', 'fa fa-linkedin-square'), ('fa fa-facebook-official', 'fa fa-facebook-official'), ('fa fa-instagram', 'fa fa-instagram'), ('fa fa-codepen', 'fa fa-codepen'), ('fa fa-google-plus-official', 'fa fa-google-plus-official'), ('fa fa-jsfiddle', 'fa fa-jsfiddle'), ('fa fa-medium', 'fa fa-medium'), ('fa fa-pinterest', 'fa fa-pinterest'), ('fa fa-quora', 'fa fa-quora'), ('fa fa-reddit', 'fa fa-reddit'), ('fa fa-scribd', 'fa fa-scribd'), ('fa fa-snapchat', 'fa fa-snapchat'), ('fa fa-skype', 'fa fa-skype'), ('fa fa-slideshare', 'fa fa-slideshare'), ('fa fa-slack', 'fa fa-slack'), ('fa fa-stack-overflow', 'fa fa-stack-overflow'), ('fa fa-telegram', 'fa fa-telegram'), ('fa fa-twitter', 'fa fa-twitter'), ('fa fa-tumblr-square', 'fa fa-tumblr-square'), ('fa fa-whatsapp', 'fa fa-whatsapp'), ('fa fa-wordpress', 'fa fa-wordpress'), ('fa fa-yahoo', 'fa fa-yahoo'), ('fa fa-youtube', 'fa fa-youtube')], max_length=200, null=True),
        ),
    ]
