# Generated by Django 3.0.10 on 2021-04-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210419_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='certificate_from',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Got certificate from'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='certificate_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Got certificate in'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='certificate_url',
            field=models.URLField(blank=True, null=True, verbose_name='Any URL of certificate or anything'),
        ),
        migrations.AlterField(
            model_name='education',
            name='Affiliated_to',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Affiliated to (CBSE,GGISPU,SHARDA etc)'),
        ),
        migrations.AlterField(
            model_name='education',
            name='Result',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Enter the result (percentage ,CGPA)'),
        ),
        migrations.AlterField(
            model_name='education',
            name='Year_pass',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Year of passing'),
        ),
        migrations.AlterField(
            model_name='education',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Enter your qualification (10h,12th,BCA,MCA etc)'),
        ),
        migrations.AlterField(
            model_name='internships',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Enter Company name'),
        ),
        migrations.AlterField(
            model_name='internships',
            name='is_working',
            field=models.BooleanField(blank=True, verbose_name='Tick if currently working'),
        ),
        migrations.AlterField(
            model_name='internships',
            name='linkedin_1_url',
            field=models.URLField(blank=True, null=True, verbose_name="Enter company's Linkedin Profile"),
        ),
        migrations.AlterField(
            model_name='internships',
            name='post',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Enter the post '),
        ),
        migrations.AlterField(
            model_name='intro',
            name='contact',
            field=models.CharField(blank=True, max_length=10, verbose_name='Contact No. :'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Describe yourself'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='e_mail',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email ID'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='exp',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Experience (Years)'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=200),
        ),
        migrations.AlterField(
            model_name='intro',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/', verbose_name='Set a portfolio image'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Enter your Name'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='media/files/'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='tagline',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Do you want to add a tagline '),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='c_img2',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='company_name1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Enter Company name you worked as employee'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='linkedin_2_url',
            field=models.URLField(blank=True, null=True, verbose_name="Enter company's Linkedin Profile"),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='package',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='post1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Enter the post '),
        ),
        migrations.AlterField(
            model_name='key_achievements',
            name='achievement_in',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Enter your achievements'),
        ),
        migrations.AlterField(
            model_name='key_specialization',
            name='specialization_in',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Enter the technology in which you are specialized'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='proj_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Project description'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='proj_url',
            field=models.URLField(blank=True, verbose_name='Do you want to add a link of your project like git or any other'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Enter the tittle for your project'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_tech',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Main Technology used in your project'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='software',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='List the key software(python,flask,selenium etc)'),
        ),
        migrations.AlterField(
            model_name='query',
            name='query_contact',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Enter your phone number'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_in',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Enter the list of  your skill'),
        ),
        migrations.AlterField(
            model_name='social_url',
            name='url_link',
            field=models.URLField(blank=True, null=True, verbose_name='any social URL link (facebook,github,linkedin,instagram etc)'),
        ),
        migrations.AlterField(
            model_name='trait',
            name='traits_in',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Enter the list of  your traits'),
        ),
    ]
