# Generated by Django 3.0.10 on 2021-04-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210419_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Enter city'),
        ),
    ]
