# Generated by Django 3.0.10 on 2021-04-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210419_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Do you want Set a  image'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='is_show2',
            field=models.BooleanField(verbose_name='Tick if you want to show it on portfolio'),
        ),
        migrations.AlterField(
            model_name='education',
            name='is_show',
            field=models.BooleanField(verbose_name='Tick if you want to show it on portfolio'),
        ),
        migrations.AlterField(
            model_name='internships',
            name='is_show6',
            field=models.BooleanField(verbose_name='Tick if  you want to show it on portfolio'),
        ),
        migrations.AlterField(
            model_name='key_achievements',
            name='is_show3',
            field=models.BooleanField(verbose_name='Tick if you want to show it on portfolio'),
        ),
        migrations.AlterField(
            model_name='key_specialization',
            name='is_show1',
            field=models.BooleanField(verbose_name='Tick if you want to show it on portfolio'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Project ended on'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='is_show4',
            field=models.BooleanField(verbose_name='Tick if you want to show it on portfolio'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='is_upcoming',
            field=models.BooleanField(verbose_name='Tick if you are planning or starting to work on it'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='is_work',
            field=models.BooleanField(verbose_name='Tick if you are working on it'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Started project on'),
        ),
        migrations.AlterField(
            model_name='social_url',
            name='is_show5',
            field=models.BooleanField(verbose_name='Tick if you want to show it on portfolio'),
        ),
    ]
