# Generated by Django 3.0.10 on 2021-04-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210419_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internships',
            name='c_img1',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Do you want to upload a image'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='img7',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Do you want Set a  image'),
        ),
    ]
