# Generated by Django 3.0.10 on 2021-04-19 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210419_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'verbose_name': 'My Certificates'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='internships',
            options={'verbose_name': 'My Internships'},
        ),
        migrations.AlterModelOptions(
            name='intro',
            options={'verbose_name': 'Introduction'},
        ),
        migrations.AlterModelOptions(
            name='jobs',
            options={'verbose_name': 'My Jobs'},
        ),
        migrations.AlterModelOptions(
            name='key_achievements',
            options={'verbose_name': 'Key Achievements'},
        ),
        migrations.AlterModelOptions(
            name='key_specialization',
            options={'verbose_name': 'Key Specialization'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'My Projects'},
        ),
        migrations.AlterModelOptions(
            name='query',
            options={'verbose_name': ' Query'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'My Skills'},
        ),
        migrations.AlterModelOptions(
            name='social_url',
            options={'verbose_name': 'My Social URL'},
        ),
        migrations.AlterModelOptions(
            name='trait',
            options={'verbose_name': 'My Traits'},
        ),
    ]
