# Generated by Django 3.0.10 on 2021-04-19 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210419_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'verbose_name': 'My Certificate'},
        ),
        migrations.AlterModelOptions(
            name='internships',
            options={'verbose_name': 'My Internship'},
        ),
        migrations.AlterModelOptions(
            name='jobs',
            options={'verbose_name': 'My Job'},
        ),
        migrations.AlterModelOptions(
            name='key_achievements',
            options={'verbose_name': 'Key Achievement'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'My Project'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'My Skill'},
        ),
        migrations.AlterModelOptions(
            name='trait',
            options={'verbose_name': 'My Trait'},
        ),
    ]
